site_name: Unifont Utils

site_url: !ENV READTHEDOCS_CANONICAL_URL

nav:
    - 开始: index.md
    - 字形: glyph.md
    - 字形集: glyph_set.md

theme:
    name: material
    language: zh
    custom_dir: docs/overrides

extra_css:
    - stylesheets/readthedocs.css

extra_javascript:
    - javascript/readthedocs.js
