site_name: Unifont Utils

site_url: !ENV READTHEDOCS_CANONICAL_URL

theme:
    name: material
    language: zh
    custom_dir: docs/overrides

extra_css:
    - stylesheets/readthedocs.css

extra_javascript:
    - javascript/readthedocs.js
